GET http://localhost:7070/exercise

### get by id

GET http://localhost:7070/exercise/1

### create

POST http://localhost:7070/exercise
content-type: application/json

{
  "name": "Push Up",
  "description": "Push Up description",
  "mediaPath": null,
  "intensity": 5
}

### update

PUT http://localhost:7070/exercise/10
content-type: application/json

{
  "name": "Push Up",
  "description": "Push Up description, but updated right",
  "mediaPath": null,
  "intensity": 5
}

### delete

DELETE http://localhost:7070/exercise/7

### add relation

POST http://localhost:7070/exercise/muscle?exerciseId=1&muscleId=1

### get muscle by exercise id

GET http://localhost:7070/exercise/1/muscle

### AUTHORIZATION

POST http://localhost:7070/auth/register
content-type: application/json

{
  "username": "admin",
  "password": "admin1234",
  "role": "ADMIN"
}

###

POST http://localhost:7070/auth/login
content-type: application/json

{
  "username": "admin",
  "password": "admin1234"
}

### perform update with authorization

POST http://localhost:7070/exercise
content-type: application/json

{
  "name": "blabla",
  "description": "Push Up description, but not updated right",
  "mediaPath": null,
  "intensity": 5
}
### Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDIyOTMzMzAsImlhdCI6MTcwMjI4NjEzMCwidXNlcm5hbWUiOiJhZG1pbiJ9.PsHk9LIJhNTkydUkwynsJkJ4PdPRY3aMz58TO-vv0fk

### get all muscles

GET http://localhost:7070/muscle