GET http://localhost:7070/exercise

### get by id

GET http://localhost:7070/exercise/1

### create

POST http://localhost:7070/exercise
content-type: application/json

{
  "name": "Push Up",
  "description": "Push Up description",
  "mediaPath": null,
  "intensity": 5
}

### create equipment

POST http://localhost:7070/equipment
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDMxNjQ2NzIsImlhdCI6MTcwMzE1NzQ3MiwidXNlcm5hbWUiOiJhZG1pbiJ9.acqq1h_B78J4mTorkVtIqlNDR0F4MBzKowlP4q2VHVs

{
  "name": "Bar",
  "description": "Bar description",
  "mediaPath": null
}

### update equipment

PUT http://localhost:7070/equipment/4
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDMxNjQ2NzIsImlhdCI6MTcwMzE1NzQ3MiwidXNlcm5hbWUiOiJhZG1pbiJ9.acqq1h_B78J4mTorkVtIqlNDR0F4MBzKowlP4q2VHVs

{
  "name": "Bar",
  "description": "Bar description, but updated",
  "mediaPath": null
}

### update

PUT http://localhost:7070/exercise/10
content-type: application/json

{
  "name": "Push Up",
  "description": "Push Up description, but updated right",
  "mediaPath": null,
  "intensity": 5
}

### delete

DELETE http://localhost:7070/exercise/7

### add relation

POST http://localhost:7070/exercise/muscle?exerciseId=1&muscleId=1,2,3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDMwNzQzMTAsImlhdCI6MTcwMzA2NzExMCwidXNlcm5hbWUiOiJhZG1pbiJ9.Pl6IkJHMTEVn0hJR7Aure9Rw87SUeoB5PLRcjFAMPTk

### add equipment relation

POST http://localhost:7070/exercise/equipment?exerciseId=1&equipmentId=1,2,3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDMwNzU5MDIsImlhdCI6MTcwMzA2ODcwMiwidXNlcm5hbWUiOiJhZG1pbiJ9.ipK9xz87it_tUxQmZUfWIGsYLVCnRY-AhGi2qeWrtEM

### add type to exercise

POST http://localhost:7070/exercise/type?exerciseId=1&typeId=1,2,3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDMwNzU5MDIsImlhdCI6MTcwMzA2ODcwMiwidXNlcm5hbWUiOiJhZG1pbiJ9.ipK9xz87it_tUxQmZUfWIGsYLVCnRY-AhGi2qeWrtEM

### get muscle by exercise id

GET http://localhost:7070/exercise/1/muscle

### AUTHORIZATION

POST http://localhost:7070/auth/register
content-type: application/json

{
  "username": "admin",
  "password": "admin1234",
  "role": "ADMIN"
}

###

POST http://localhost:7070/auth/login
content-type: application/json

{
  "username": "admin",
  "password": "admin1234"
}

### perform update with authorization

POST http://localhost:7070/exercise
content-type: application/json

{
  "name": "blabla",
  "description": "Push Up description, but not updated right",
  "mediaPath": null,
  "intensity": 5
}
### Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDIyOTMzMzAsImlhdCI6MTcwMjI4NjEzMCwidXNlcm5hbWUiOiJhZG1pbiJ9.PsHk9LIJhNTkydUkwynsJkJ4PdPRY3aMz58TO-vv0fk

### get all muscles

GET http://localhost:7070/muscle

### search exercises by muscle pattern

GET http://localhost:7070/search/exercise/byMuscle?pattern=lat

### search exercises by equipment pattern

GET http://localhost:7070/search/exercise/byEquipment?pattern=bar

### search exercises by name pattern

GET http://localhost:7070/search/exercise/byName?pattern=ben

### search muslce by name

GET http://localhost:7070/search/muscle/byName?pattern=issi

### search equipment by name

GET http://localhost:7070/search/equipment/byName?pattern=bar

###

GET http://localhost:7070/search/type/byName?pattern=sth

### search musclegroup by pattern

GET http://localhost:7070/search/musclegroup/byName?pattern=he

### search muscles by equipment

GET http://localhost:7070/search/muscle/byequipment?pattern=bar

### search muscles by exercise pattern

GET http://localhost:7070/search/muscle/byexercise?pattern=squ

### search equipment by muscle pattern

GET http://localhost:7070/search/equipment/bymuscle?pattern=

### search equipment by exercise pattern

GET http://localhost:7070/search/equipment/byexercise?pattern=qua
